name: CI - Pull Request

on:
  pull_request

jobs:
  maven-build:
    uses: ./.github/workflows/_maven-build.yml
    with:
      java_version: '17'
  docker-build-push:
    uses: ./.github/workflows/_docker-build-push.yml
    with:
      push_to_ghcr: false
      image_name: oriso-tenantservice
